main: com.cavetale.resident.ResidentPlugin

name: Resident
version: 0.1
description: Talking Villager Zones
api-version: '1.20'

author: StarTux
website: https://github.com/StarTux/Resident

depend: [Core, Mytems]
softdepend: []

commands:

  resident:
    aliases: []
    description: Resident Command
    permission: resident.resident
    usage: |-
      /resident

permissions:

  resident.resident:
    description: Use /resident
    default: op
